### ISSUE TITLE
mobile 

### ISSUE THREAD

**Issue by gedw99** [kaepora/resilience#12]
Can you do this on mobiles ? I mean set a proxy at the OS level ?

**Comment by meonwax** [comment]
Should work, at least on [Android](https://www.howtogeek.com/295048/how-to-configure-a-proxy-server-on-android/).

**Comment by ivanhercaz** [comment]
I think Blokada achieve this function. Check [Blokada](https://blokada.org).

**Comment by kaepora** [comment]
Yeah, that's the thing. I think there's already a bunch of good apps that do this well on Android and iOS.

**Comment by ivanhercaz** [comment]
Although I prefer the idea of Blokada, it isn't in iOS, so I recommend for this platform the free version of AdGuard.
