### ISSUE TITLE
Package gdk-3.0 was not found in the pkg-config search path

### ISSUE THREAD

**Issue by ivanhercaz** [kaepora/resilience#4]
Although this issue might be related with #2, I think it is necessary to address this specific problem.

When I run `make dependencies` I get the next error:
```
[Resilience] Installing dependencies...# pkg-config --cflags  -- gdk-3.0 glib-2.0 gobject-2.0
Package gdk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gdk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdk-3.0' found
pkg-config: exit status 1
make: *** [Makefile:8: dependencies] Error 2
```

That sounds strange to me, so I run `apt-get install gdk-3.0 glib-2.0 gobject-2.0` (I use Debian 10) and the system said me that I already have installed the next packages:

```
gir1.2-glib-2.0 ya está en su versión más reciente (1.58.3-2).
gir1.2-gtk-3.0 ya está en su versión más reciente (3.24.5-1).
gir1.2-spiceclientglib-2.0 ya está en su versión más reciente (0.35-2).
libspice-client-glib-2.0-8 ya está en su versión más reciente (0.35-2).
```

So it just installed `libqt5glib-2.0-0 libspice-client-glib-2.0-dev libspice-protocol-dev`. Then I run again `make dependencies` and happened the same error quoted above.

**Comment by kaepora** [comment]
I think this is actually needed to [build the systray dependency under Linux](https://github.com/getlantern/systray#linux).

**Comment by ivanhercaz** [comment]
If I make `ls $PKG_CONFIG_PATH` I get:

`gdk-sharp-3.0.pc  glib-sharp-3.0.pc  libgdiplus.pc  libquvi-scripts-0.9.pc  libR.pc  pm-utils.pc  py3cairo.pc`

I also install `libgdk3.0-cil-dev` and `libgdk3.0-cil` to check if it could solve the problem but not.

**Comment by kaepora** [comment]
@ivanhercaz Really happy to have you help with testing. Please let me know what you discover.

**Comment by ivanhercaz** [comment]
> @ivanhercaz Really happy to have you help with testing. Please let me know what you discover.

It's a pleasure! It seems a very interesting tool, so if I can help you with testing, it is nice for both :) Thank you for its development.

> I think this is actually needed to build the systray dependency under Linux.

I run `apt-get install libgtk-3-dev libappindicator3-dev` and then `make dependencies` and now I only got:

```
[Resilience] Installing dependencies... OK
```

So I think all the dependencies are installed now without problems. Then I got this error after run `make all`:

```
[Resilience] Building Resilience... internal/app/resilience/denier.go:13:2: cannot find package "rand" in any of:
```

But it seems to be fixed in #1, so I pull the repository to update the code and then the result of the `make all` instruction is:

```
[Resilience] Building Resilience...       OK
```

And now I can run Resilience with `cmd/resilience/resilience`! I will keep my eyes in possible bugs or whatever to improve. Now I am going to read about how to do it:

>  In order to use Resilience, you must configure it as your system's HTTP and HTTPS proxy by setting them both to localhost:7341. People testing an early alpha already know how to do this, but better help instructions will come in due course.

**Comment by ivanhercaz** [comment]
kkkj

**Comment by kolanos** [comment]
@ivanhercaz The `getlantern/systray` depends on:

```bash
sudo apt-get install libgtk-3-dev libappindicator3-dev
```

If you have both those dependencies and it still doesn't build then you may want to create an issue for that project:
https://github.com/getlantern/systray

The README there says it has been tested with Debian 7.6 and Ubuntu 14.10.

**Comment by ivanhercaz** [comment]
Hi @kolanos :)

Thank you for your answer, but I already solved it installing the packages you mentioned, as you can check in my last message before to close this issue.

> The README there says it has been tested with Debian 7.6 and Ubuntu 14.10.

Fortunately, it works in Debian 10 too :smile:
